=== Nykage/XML/harjoitukset/harjoitukset 1/bill.dtd
<!DOCTYPE bill[
    <!ELEMENT bill (sender, recipient, message, cost)>
    <!ATTLIST bill type (phone bill|electricity bill) #REQUIRED>
    <!ELEMENT sender (#PCDATA)>
    <!ELEMENT recipient (#PCDATA)>
    <!ELEMENT message (#PCDATA)>
    <!ATTLIST message class (warning|normal) #IMPLIED>
    <!ELEMENT cost (net-cost, taxes, gross-cost)>
    <!ELEMENT net-cost (#PCDATA)>
    <!ELEMENT taxes (#PCDATA)>
    <!ELEMENT gross-cost (#PCDATA)>
]>

=== Nykage/XML/harjoitukset/harjoitukset 1/bill.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<?xml-stylesheet type = "text/css" href="bill.css"?>
<!DOCTYPE bill SYSTEM "bill.dtd">

<bill type="phone bill">
    <sender>Seller</sender>
    <recipient>Customer</recipient>
    <message class="warning">
        You haven't paid your last phone bill.
        Please pay in 14 days or we will take consequences.
    </message>
    <cost>
        <net-cost>
        Net-cost: 10,00 €
        </net-cost>
        <taxes>
        Taxes: 2,00 €
        </taxes>
        <gross-cost>
        Cost: 12,00 €
        </gross-cost>
    </cost>
</bill>
