=== Nykage/XML/harjoitukset/harjoitukset 1/lentolippu.dtd
<!DOCTYPE lentolippu [
    <!ELEMENT lentolippu (lento, matkustaja, hintatiedot)>
    <!ELEMENT lento (mista, minne, lahtoaika)>
    <!ELEMENT lahtoaika (kuu, paiva, tunti, min)>
    <!ELEMENT matkustaja (sukunimi, etunimi)>
    <!ELEMENT hintatiedot (hinta, vero)>
    <!ELEMENT kuu (#PCDATA)>
    <!ELEMENT paiva (#PCDATA)>
    <!ELEMENT tunti (#PCDATA)>
    <!ELEMENT min (#PCDATA)>
    <!ELEMENT sukunimi (#PCDATA)>
    <!ELEMENT etunimi (#PCDATA)>
    <!ELEMENT hinta (#PCDATA)>
    <!ELEMENT vero (#PCDATA)>
    <!ATTLIST mista alue (eurooppa|amerikka|aasia) #REQUIRED>
    <!ATTLIST hintatiedot class (1|2) #REQUIRED>
]>

=== Nykage/XML/harjoitukset/harjoitukset 1/lentolippu.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<?xml-stylesheet type = "text/css" href="lentolippu.css"?>
<!DOCTYPE lentolippu SYSTEM "lentolippu.dtd">

<lentolippu>
    <lento>
        <mista alue="eurooppa"></mista>
        <minne></minne>
        <lahtoaika>
            <kuu></kuu>
            <paiva></paiva>
            <tunti></tunti>
            <min></min>
        </lahtoaika>
    </lento>
    <matkustaja>
        <sukunimi></sukunimi>
        <etunimi></etunimi>
    </matkustaja>
    <hintatiedot class="2">
        <hinta></hinta>
        <vero></vero>
    </hintatiedot>
</lentolippu>
